"""Canonical student-facing metadata for algorithm pages.

The portal generator consumes this file directly.  Public titles are plain
language; internal source identifiers never appear in generated pages.
"""

ALGORITHM_VARIANTS = [
    ("PAT-DATA-ASM-OBJECTS-001", "Initialized, constant and reserved ARM objects", "ARM ABI and memory", "Choose DCB, DCW, DCD or SPACE from the object width and initialization requirement.", "O(n) when scanning the object"),
    ("PAT-ALG-WIDE-DIVISION-001", "Restoring division quotient and remainder", "Arithmetic and number theory", "Shift one dividend bit into the remainder, subtract when possible, and set the quotient bit.", "O(word bits)"),
    ("PAT-MEM-PACKED-TRANSPOSE-001", "Packed matrix row and column addressing", "Arrays and matrices", "Translate row/column coordinates into a packed bit position before moving the bit.", "O(rows x columns)"),
    ("PAT-ALG-PACKED-MATMUL-001", "GF(2) row-column dot products", "Arrays and matrices", "AND corresponding bits and XOR the products instead of using integer addition.", "O(n cubed)"),
    ("PAT-ALG-DFS-STACK-001", "Explicit-stack graph traversal", "Graphs", "Replace recursion with a bounded stack and mark a vertex when it is accepted.", "O(V + E)"),
    ("PAT-ALG-COMPONENT-MERGE-001", "Seven-argument component merge", "ARM ABI and memory", "Map the first four arguments to registers and later arguments from the caller stack.", "O(n)"),
    ("PAT-ALG-LCG-001", "Five-argument LCG and stack argument", "Recursion and dynamic programming", "Compute the recurrence with the exact unsigned width and load the fifth argument using the post-prologue stack offset.", "O(1)"),
    ("PAT-ALG-RUN-LENGTH-001", "Run-length final-run handling", "Embedded streams and signals", "Emit the active run both on a value change and after the input loop finishes.", "O(n)"),
    ("PAT-ALG-LOOK-AND-SAY-001", "Bounded look-and-say generation", "Recursion and dynamic programming", "Count each equal run and verify output capacity before writing count/value pairs.", "O(n)"),
    ("PAT-ALG-INDIRECT-RECURRENCE-001", "Indirect-index recurrence safety", "Recursion and dynamic programming", "Validate every computed dependency index before loading an earlier term.", "O(n)"),
    ("PAT-ALG-REDUCTION-001", "Single-pass minimum, maximum and sum", "Arrays and matrices", "Seed extrema from the first element and update all reductions in one bounded traversal.", "O(n)"),
    ("PAT-ALG-CONSUME-ONCE-MATCH-001", "Duplicate-safe Bulls and Cows matching", "Arrays and matrices", "Mark exact matches first, then consume each unmatched position at most once.", "O(n squared)"),
    ("PAT-ALG-LINEAR-SEARCH-001", "First matching array element", "Searching and selection", "Stop at the first equal element and return a deliberate not-found sentinel.", "O(n)"),
    ("PAT-ALG-LINEAR-SEARCH-001", "Last matching array element", "Searching and selection", "Scan backwards or retain the latest matching index.", "O(n)"),
    ("PAT-ALG-LINEAR-SEARCH-001", "Collect every matching index", "Searching and selection", "Count all matches while writing only within the supplied output capacity.", "O(n)"),
    ("PAT-ALG-BINARY-SEARCH-001", "Lower bound insertion position", "Searching and selection", "Maintain a half-open interval and keep the first value not less than the key.", "O(log n)"),
    ("PAT-ALG-BINARY-SEARCH-001", "Exact binary search from lower bound", "Searching and selection", "Find lower bound, then verify that the candidate is in range and equal.", "O(log n)"),
    ("PAT-ALG-ARRAY-ROTATION-001", "Left array rotation by reversal", "Arrays and matrices", "Reverse the two segments, then reverse the complete array.", "O(n)"),
    ("PAT-ALG-ARRAY-ROTATION-001", "Right array rotation with normalized distance", "Arrays and matrices", "Reduce the distance modulo length and convert right rotation to a left rotation.", "O(n)"),
    ("PAT-ALG-GCD-LCM-001", "Overflow-aware least common multiple", "Arithmetic and number theory", "Divide by the GCD before multiplying and check the widened product.", "O(log min(a,b))"),
    ("PAT-ALG-PRIME-FACTORIZATION-001", "Trial prime factorization", "Arithmetic and number theory", "Divide repeated factors and stop when divisor exceeds n/divisor.", "O(sqrt(n))"),
    ("PAT-ALG-DECIMAL-DIGITS-001", "Decimal extraction and reconstruction", "Arithmetic and number theory", "Use remainder ten for the next digit and division ten to advance.", "O(number of digits)"),
    ("PAT-ALG-DECIMAL-DIGITS-001", "Kaprekar digit ordering step", "Arithmetic and number theory", "Count four decimal digits, rebuild descending and ascending values, then subtract.", "O(number of digits)"),
    ("PAT-ALG-POPCOUNT-PARITY-001", "Parity from population count", "Bits and fixed point", "Toggle parity once per removed set bit.", "O(number of set bits)"),
    ("PAT-ALG-BITFIELD-001", "Bitfield extraction", "Bits and fixed point", "Shift the field to bit zero and mask exactly its width.", "O(1)"),
    ("PAT-ALG-BITFIELD-001", "Bitfield insertion without neighbor damage", "Bits and fixed point", "Clear only the destination mask, then OR the masked shifted value.", "O(1)"),
    ("PAT-ALG-SATURATING-ARITHMETIC-001", "Saturating addition", "Bits and fixed point", "Compute in a wider type, then clamp before narrowing.", "O(1)"),
    ("PAT-ALG-PREFIX-SUM-001", "Constant-time range sums", "Arrays and matrices", "Store prefix[0]=0 and subtract two prefix entries for each half-open range.", "O(n) build, O(1) query"),
    ("PAT-ALG-HISTOGRAM-MODE-001", "Frequency table and deterministic mode", "Arrays and matrices", "Count bounded values and define how ties are resolved.", "O(n + range)"),
    ("PAT-ALG-MOVING-AVERAGE-001", "Sliding-window running sum", "Embedded streams and signals", "Add the entering sample and subtract the leaving sample instead of recomputing the window.", "O(n)"),
    ("PAT-ALG-STRING-PRIMITIVES-001", "Bounded string copy", "Strings", "Reserve one byte for the terminator and fail before an out-of-capacity write.", "O(n)"),
    ("PAT-ALG-STRING-PRIMITIVES-001", "Lexicographic byte comparison", "Strings", "Stop on the first unsigned-byte difference or the shared terminator.", "O(n)"),
    ("PAT-ALG-MEMMOVE-001", "Overlap-safe backward copy", "Arrays and matrices", "Copy from the end only when the destination begins inside the source range.", "O(n)"),
    ("PAT-ALG-CHECKSUM-CRC-001", "Additive versus XOR checksum", "Bits and fixed point", "Update both accumulators per byte and keep the requested width explicit.", "O(n)"),
    ("PAT-DS-RING-BUFFER-001", "ISR-to-main ring buffer", "Data structures", "Keep head, tail and count bounded and give producer and consumer separate ownership.", "O(1) per operation"),
    ("PAT-DS-CIRCULAR-QUEUE-001", "Queue wraparound", "Data structures", "Advance indexes modulo capacity and distinguish empty from full with a count.", "O(1) per operation"),
    ("PAT-DS-UNION-FIND-001", "Path compression and union by rank", "Graphs", "Compress find paths and attach the shallower root during union.", "Near O(1) amortized"),
    ("PAT-ALG-KNAPSACK-001", "One-row zero-one knapsack", "Recursion and dynamic programming", "Traverse capacity backwards so each item is consumed at most once.", "O(items x capacity)"),
    ("PAT-ALG-COIN-CHANGE-001", "Minimum-coin dynamic programming", "Recursion and dynamic programming", "Build from amount zero and ignore unreachable predecessor states.", "O(coins x amount)"),
    ("PAT-ALG-EDIT-DISTANCE-001", "Two-row edit distance", "Recursion and dynamic programming", "Use insertion, deletion and substitution transitions while retaining only two rows.", "O(nm) time, O(m) space"),
]


EXTRA_ALGORITHMS = [
    {
        "slug": "insertion-sort",
        "title": "Insertion sort",
        "family": "Sorting",
        "summary": 'Sort signed words ascending in place, stably. Null input is a no-op; n is the number of accessible words.',
        "recognition": '1. Save the next key.\n2. Shift strictly larger prefix values right.\n3. Insert the key in its gap.',
        "method": '1. Save the next key.\n2. Shift strictly larger prefix values right.\n3. Insert the key in its gap.',
        "complexity": 'O(n squared) worst case, O(n) best case, O(1) extra space.',
        "history": 'Possible variation',
        "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nvoid insertion_sort(int *a, size_t n) {\n  size_t i;\n  if (a == NULL) return;\n  for (i = 1; i < n; ++i) {\n    int key = a[i];\n    size_t j = i;\n    while (j != 0u && a[j - 1u] > key) {\n      a[j] = a[j - 1u];\n      --j;\n    }\n    a[j] = key;\n  }\n}\n',
    },
    {
        "slug": "cocktail-sort", "title": "Cocktail shaker sort", "family": "Sorting",
        "summary": 'Stable ascending adjacent-swap sort. Null input is a no-op; arrays of length below two are unchanged.',
        "recognition": '1. Sweep large values to the right.\n2. Shrink the high bound.\n3. Sweep small values left and shrink the low bound.',
        "method": '1. Sweep large values to the right.\n2. Shrink the high bound.\n3. Sweep small values left and shrink the low bound.',
        "complexity": 'O(n squared) time and O(1) space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nvoid cocktail_sort(int *a, size_t n) {\n  size_t lo = 0u, hi = n;\n  int changed = 1;\n  if (a == NULL) return;\n  while (changed && hi > lo + 1u) {\n    size_t i;\n    changed = 0;\n    for (i = lo + 1u; i < hi; ++i) if (a[i - 1u] > a[i]) { int t=a[i-1u]; a[i-1u]=a[i]; a[i]=t; changed=1; }\n    if (!changed) break;\n    --hi; changed = 0;\n    for (i = hi - 1u; i > lo; --i) if (a[i - 1u] > a[i]) { int t=a[i-1u]; a[i-1u]=a[i]; a[i]=t; changed=1; }\n    ++lo;\n  }\n}\n',
    },
    {
        "slug": "shell-sort", "title": "Shell sort", "family": "Sorting",
        "summary": 'Ascending signed-word sort using halved gaps. In place and not guaranteed stable; null input is a no-op.',
        "recognition": '1. Choose gap=n/2.\n2. Apply insertion sort to each gap-separated subsequence.\n3. Halve the gap through one.',
        "method": '1. Choose gap=n/2.\n2. Apply insertion sort to each gap-separated subsequence.\n3. Halve the gap through one.',
        "complexity": 'Depends on the gap sequence; O(n squared) for the simple halving sequence.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nvoid shell_sort(int *a, size_t n) {\n  size_t gap, i;\n  if (a == NULL) return;\n  for (gap = n / 2u; gap != 0u; gap /= 2u)\n    for (i = gap; i < n; ++i) {\n      int value = a[i]; size_t j = i;\n      while (j >= gap && a[j-gap] > value) { a[j] = a[j-gap]; j -= gap; }\n      a[j] = value;\n    }\n}\n',
    },
    {
        "slug": "radix-sort", "title": "LSD radix sort", "family": "Sorting",
        "summary": 'Stable unsigned sort using four byte passes. a and tmp each hold n words and must not overlap; exact alias is rejected. Empty input succeeds. Uses 256 word counters on the stack.',
        "recognition": '1. Count byte frequencies.\n2. Turn counts into starting offsets.\n3. Scatter stably into scratch and copy back, for shifts 0,8,16,24.',
        "method": '1. Count byte frequencies.\n2. Turn counts into starting offsets.\n3. Scatter stably into scratch and copy back, for shifts 0,8,16,24.',
        "complexity": 'O(4n + 4x256) time and O(n + 256) space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stdint.h>\n#include <stddef.h>\nint radix_sort_u32(uint32_t*a,size_t n,uint32_t*tmp){if(!n)return 1;if(!a||!tmp||a==tmp)return 0;size_t count[256];for(unsigned shift=0;shift<32;shift+=8){for(size_t b=0;b<256;b++)count[b]=0;for(size_t i=0;i<n;i++)count[(a[i]>>shift)&255]++;size_t sum=0;for(size_t b=0;b<256;b++){size_t c=count[b];count[b]=sum;sum+=c;}for(size_t i=0;i<n;i++){unsigned b=(a[i]>>shift)&255;tmp[count[b]++]=a[i];}for(size_t i=0;i<n;i++)a[i]=tmp[i];}return 1;}\n',
    },
    {
        "slug": "upper-bound-equal-range", "title": "Upper bound and equal range", "family": "Searching and selection",
        "summary": 'Ascending signed input; return the first index with value>key, or n. Null returns zero. This entry supplies upper bound; combine with the existing lower-bound routine for an equal range.',
        "recognition": '1. Maintain [lo,hi).\n2. Move lo past values <=key.\n3. Otherwise lower hi.',
        "method": '1. Maintain [lo,hi).\n2. Move lo past values <=key.\n3. Otherwise lower hi.',
        "complexity": 'O(log n) time and O(1) space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nsize_t upper_bound_i32(const int *a,size_t n,int key){size_t lo=0u,hi=n;if(a==NULL)return 0u;while(lo<hi){size_t m=lo+(hi-lo)/2u;if(a[m]<=key)lo=m+1u;else hi=m;}return lo;}\n',
    },
    {
        "slug": "quickselect", "title": "Quickselect", "family": "Searching and selection",
        "summary": 'Return 1 and the zero-based kth signed value, rearranging the input. Invalid pointers or k>=n return 0 without writing. Not stable.',
        "recognition": '1. Partition around the last value.\n2. Return if its final rank is k.\n3. Continue only on the side containing k.',
        "method": '1. Partition around the last value.\n2. Return if its final rank is k.\n3. Continue only on the side containing k.',
        "complexity": 'O(n) average and O(n squared) worst case.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nint quickselect(int *a,size_t n,size_t k,int *out){size_t lo=0u,hi;if(a==NULL||out==NULL||k>=n)return 0;hi=n-1u;for(;;){size_t i,j=lo;int p=a[hi];for(i=lo;i<hi;++i)if(a[i]<p){int t=a[i];a[i]=a[j];a[j++]=t;}a[hi]=a[j];a[j]=p;if(j==k){*out=a[j];return 1;}if(k<j)hi=j-1u;else lo=j+1u;}}\n',
    },
    {
        "slug": "rectangular-matrix-transpose", "title": "Rectangular matrix transpose", "family": "Arrays and matrices",
        "summary": 'Transpose a row-major signed-word matrix into disjoint output with rows*cols words. Zero dimensions succeed. Reject null nonempty inputs, exact aliasing, and products exceeding the 32-bit word-address range.',
        "recognition": '1. Read input[r*cols+c].\n2. Write output[c*rows+r].',
        "method": '1. Read input[r*cols+c].\n2. Write output[c*rows+r].',
        "complexity": 'O(rows x columns) time and matching output space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\nint matrix_transpose(const int*a,size_t r,size_t c,int*out){if(!r||!c)return 1;if(!a||!out||a==out||r>0x3fffffffu/c)return 0;for(size_t i=0;i<r;i++)for(size_t j=0;j<c;j++)out[j*r+i]=a[i*c+j];return 1;}\n',
    },
    {
        "slug": "topological-sort", "title": "Topological sort", "family": "Graphs",
        "summary": 'Byte adjacency matrix, n<=256. degree, queue and out each hold n words and do not overlap. Return n for a complete order; return 0 on a cycle or invalid input. A cycle may leave a valid partial order.',
        "recognition": '1. Count incoming edges.\n2. Queue vertices of indegree zero.\n3. Remove them, decrementing outgoing neighbors.',
        "method": '1. Count incoming edges.\n2. Queue vertices of indegree zero.\n3. Remove them, decrementing outgoing neighbors.',
        "complexity": 'O(V squared) for a matrix or O(V+E) for adjacency lists.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\nsize_t topological_sort(const uint8_t*a,size_t n,size_t*d,size_t*q,size_t*out){if(!a||!d||!q||!out||n>256)return 0;size_t h=0,t=0;for(size_t i=0;i<n;i++){d[i]=0;for(size_t j=0;j<n;j++)d[i]+=a[j*n+i]!=0;if(!d[i])q[t++]=i;}while(h<t){size_t v=q[h];out[h++]=v;for(size_t j=0;j<n;j++)if(a[v*n+j]&&!--d[j])q[t++]=j;}return h==n?h:0;}\n',
    },
    {
        "slug": "bellman-ford", "title": "Bellman-Ford shortest paths", "family": "Graphs",
        "summary": 'Directed edge list, n=1..256, valid endpoints, and n distance words. INT_MAX is unreachable and reserved. Return 0 for invalid input, reachable negative cycle or arithmetic outside INT_MIN..INT_MAX-1; failure during relaxation may leave partial distances.',
        "recognition": '1. Validate every endpoint before indexing.\n2. Relax all edges up to n-1 times, exiting if unchanged.\n3. An improvement on pass n proves a reachable negative cycle.',
        "method": '1. Validate every endpoint before indexing.\n2. Relax all edges up to n-1 times, exiting if unchanged.\n3. An improvement on pass n proves a reachable negative cycle.',
        "complexity": 'O(VE) time and O(V) distance space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stdint.h>\ntypedef struct{size_t from,to;int weight;}Edge;\nint bellman_ford(const Edge*e,size_t m,size_t n,size_t s,int*d){if(!d||(!e&&m)||s>=n||n>256||m>UINT32_MAX/12)return 0;for(size_t i=0;i<m;i++)if(e[i].from>=n||e[i].to>=n)return 0;for(size_t i=0;i<n;i++)d[i]=INT_MAX;d[s]=0;for(size_t k=1;k<=n;k++){int changed=0;for(size_t i=0;i<m;i++)if(d[e[i].from]!=INT_MAX){int64_t x=(int64_t)d[e[i].from]+e[i].weight;if(x<INT_MIN||x>=INT_MAX)return 0;if(x<d[e[i].to]){if(k==n)return 0;d[e[i].to]=(int)x;changed=1;}}if(!changed)return 1;}return 1;}\n',
    },
    {
        "slug": "floyd-warshall", "title": "Floyd-Warshall all-pairs paths", "family": "Graphs",
        "summary": 'In-place distance matrix, n<=256, positive infinity sentinel. Finite distances must be less than infinity; initialize diagonal to zero. Candidates at or above infinity remain unrepresentable. Return 0 on invalid input, signed overflow or negative cycle, possibly after partial updates.',
        "recognition": '1. For each intermediate k, visit all pairs i,j.\n2. Skip unreachable legs.\n3. Add finite legs with overflow checking and improve the distance.',
        "method": '1. For each intermediate k, visit all pairs i,j.\n2. Skip unreachable legs.\n3. Add finite legs with overflow checking and improve the distance.',
        "complexity": 'O(V cubed) time and O(V squared) matrix space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\n#include <limits.h>\nint floyd_warshall(int*d,size_t n,int inf){if(!d||n>256||inf<=0)return 0;for(size_t k=0;k<n;k++)for(size_t i=0;i<n;i++)for(size_t j=0;j<n;j++)if(d[i*n+k]!=inf&&d[k*n+j]!=inf){int64_t x=(int64_t)d[i*n+k]+d[k*n+j];if(x<INT_MIN||x>INT_MAX)return 0;if(x<d[i*n+j])d[i*n+j]=(int)x;}for(size_t i=0;i<n;i++)if(d[i*n+i]<0)return 0;return 1;}\n',
    },
    {
        "slug": "prim-mst", "title": "Prim minimum spanning tree", "family": "Graphs",
        "summary": 'Undirected symmetric weight matrix with zero meaning no edge; n=1..256. Supply n best words and n used bytes. Return MST weight, or UINT_MAX for invalid input, disconnection or unrepresentable total. UINT_MAX is reserved.',
        "recognition": '1. Start one vertex at cost zero.\n2. Add the unused vertex with smallest connection cost.\n3. Update neighbor costs and check the accumulated weight.',
        "method": '1. Start one vertex at cost zero.\n2. Add the unused vertex with smallest connection cost.\n3. Update neighbor costs and check the accumulated weight.',
        "complexity": 'O(V squared) with arrays.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <limits.h>\nunsigned prim_mst(const unsigned*w,size_t n,size_t s,unsigned*b,unsigned char*u){if(!w||!b||!u||s>=n||n>256)return UINT_MAX;for(size_t i=0;i<n;i++){b[i]=UINT_MAX;u[i]=0;}b[s]=0;unsigned total=0;for(size_t k=0;k<n;k++){size_t v=n;unsigned low=UINT_MAX;for(size_t i=0;i<n;i++)if(!u[i]&&b[i]<low){low=b[i];v=i;}if(v==n||low>=UINT_MAX-total)return UINT_MAX;u[v]=1;total+=low;for(size_t i=0;i<n;i++)if(!u[i]&&w[v*n+i]&&w[v*n+i]<b[i])b[i]=w[v*n+i];}return total;}\n',
    },
    {
        "slug": "kruskal-mst", "title": "Kruskal minimum spanning tree", "family": "Graphs",
        "summary": 'Supply edges sorted by nondecreasing weight, n=1..256, valid endpoints and n parent words. Return MST weight or UINT_MAX for invalid ordering/endpoints, disconnection or total overflow. This generic MST differs from the supplied maze-generation exam.',
        "recognition": '1. Validate ordering and endpoints.\n2. Initialize one component per vertex.\n3. Accept edges joining different roots, checking total weight.',
        "method": '1. Validate ordering and endpoints.\n2. Initialize one component per vertex.\n3. Accept edges joining different roots, checking total weight.',
        "complexity": 'O(E log E) including edge sorting.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stdint.h>\ntypedef struct{size_t u,v;unsigned w;}MstEdge;\nstatic size_t mst_root(size_t*p,size_t x){while(p[x]!=x){p[x]=p[p[x]];x=p[x];}return x;}\nunsigned kruskal_mst(const MstEdge*e,size_t m,size_t n,size_t*p){if(!p||!n||n>256||(!e&&m)||m>UINT32_MAX/12)return UINT_MAX;for(size_t i=0;i<m;i++)if(e[i].u>=n||e[i].v>=n||(i&&e[i].w<e[i-1].w))return UINT_MAX;for(size_t i=0;i<n;i++)p[i]=i;size_t used=0;unsigned total=0;for(size_t i=0;i<m&&used+1<n;i++){size_t a=mst_root(p,e[i].u),b=mst_root(p,e[i].v);if(a!=b){if(e[i].w>=UINT_MAX-total)return UINT_MAX;p[b]=a;total+=e[i].w;used++;}}return used+1==n?total:UINT_MAX;}\n',
    },
    {
        "slug": "bipartite-test", "title": "Bipartite graph test", "family": "Graphs",
        "summary": 'Undirected byte adjacency matrix, n<=256. Supply n color bytes and n queue words. Return 1 for a two-coloring across all components, or 0 on conflict or invalid input.',
        "recognition": '1. Initialize all colors to -1.\n2. BFS each uncolored component.\n3. Assign opposite colors and reject equal-color edges.',
        "method": '1. Initialize all colors to -1.\n2. BFS each uncolored component.\n3. Assign opposite colors and reject equal-color edges.',
        "complexity": 'O(V squared) for a matrix.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\nint graph_is_bipartite(const uint8_t*a,size_t n,int8_t*c,size_t*q){if(!a||!c||!q||n>256)return 0;for(size_t i=0;i<n;i++)c[i]=-1;for(size_t s=0;s<n;s++)if(c[s]<0){size_t h=0,t=0;c[s]=0;q[t++]=s;while(h<t){size_t v=q[h++];for(size_t w=0;w<n;w++)if(a[v*n+w]){if(c[w]<0){c[w]=1-c[v];q[t++]=w;}else if(c[w]==c[v])return 0;}}}return 1;}\n',
    },
    {
        "slug": "directed-cycle-detection", "title": "Directed cycle detection", "family": "Graphs",
        "summary": 'Directed byte adjacency matrix, n<=256, and n state bytes. Return 1 for a cycle, 0 otherwise or for invalid input. Initialize states internally. Recursion uses at most n helper frames.',
        "recognition": '1. Mark a vertex gray on entry.\n2. A gray neighbor proves a back edge.\n3. Recurse into white vertices, then mark the vertex black.',
        "method": '1. Mark a vertex gray on entry.\n2. A gray neighbor proves a back edge.\n3. Recurse into white vertices, then mark the vertex black.',
        "complexity": 'O(V squared) for a matrix.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\nstatic int cycle_visit(const uint8_t*a,size_t n,size_t v,uint8_t*s){s[v]=1;for(size_t w=0;w<n;w++)if(a[v*n+w]){if(s[w]==1)return 1;if(!s[w]&&cycle_visit(a,n,w,s))return 1;}s[v]=2;return 0;}\nint directed_cycle(const uint8_t*a,size_t n,uint8_t*s){if(!a||!s||n>256)return 0;for(size_t i=0;i<n;i++)s[i]=0;for(size_t i=0;i<n;i++)if(!s[i]&&cycle_visit(a,n,i,s))return 1;return 0;}\n',
    },
    {
        "slug": "a-star-grid", "title": "A-star grid search", "family": "Mazes and backtracking",
        "summary": 'Four-neighbor unit-cost grid, rows/cols=1..256, zero=passage and nonzero=wall. g and closed each have rows*cols elements and do not overlap other storage. Return 1 if the goal is reachable, with its shortest distance in g[goal]; return 0 for invalid or unreachable input. Blocked start/goal fail.',
        "recognition": '1. Set start distance to zero and other distances to UINT_MAX.\n2. Select the open cell minimizing g plus Manhattan distance.\n3. Close it and relax legal unblocked neighbors.\n4. Stop at the goal or when no open cell remains.',
        "method": '1. Set start distance to zero and other distances to UINT_MAX.\n2. Select the open cell minimizing g plus Manhattan distance.\n3. Close it and relax legal unblocked neighbors.\n4. Stop at the goal or when no open cell remains.',
        "complexity": 'O(V squared) with a simple array open set.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <limits.h>\nint astar_grid(const unsigned char*w,size_t rows,size_t cols,size_t start,size_t goal,unsigned*g,unsigned char*c){if(!w||!g||!c||!rows||!cols||rows>256||cols>256)return 0;size_t n=rows*cols;if(start>=n||goal>=n||w[start]||w[goal])return 0;for(size_t i=0;i<n;i++){g[i]=UINT_MAX;c[i]=0;}g[start]=0;for(;;){size_t v=n;unsigned best=UINT_MAX;for(size_t i=0;i<n;i++)if(!c[i]&&g[i]!=UINT_MAX){size_t r=i/cols,x=i%cols,gr=goal/cols,gx=goal%cols;unsigned h=(unsigned)((r>gr?r-gr:gr-r)+(x>gx?x-gx:gx-x));if(g[i]+h<best){best=g[i]+h;v=i;}}if(v==n)return 0;if(v==goal)return 1;c[v]=1;size_t next[4],count=0;if(v>=cols)next[count++]=v-cols;if(v+cols<n)next[count++]=v+cols;if(v%cols)next[count++]=v-1;if(v%cols+1<cols)next[count++]=v+1;for(size_t j=0;j<count;j++){size_t x=next[j];if(!w[x]&&!c[x]&&g[v]+1<g[x])g[x]=g[v]+1;}}}\n',
    },
    {
        "slug": "subset-sum", "title": "Subset-sum dynamic programming", "family": "Recursion and dynamic programming",
        "summary": 'Return whether target can be formed using each item at most once. reachable has target+1 bytes. Null inputs or target==SIZE_MAX return 0; zero-valued items do not change reachability.',
        "recognition": '1. Mark only sum zero reachable.\n2. Process each positive value.\n3. Traverse sums downward to prevent reusing that item.',
        "method": '1. Mark only sum zero reachable.\n2. Process each positive value.\n3. Traverse sums downward to prevent reusing that item.',
        "complexity": 'O(n x target) time and O(target) space.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\n#include <stdint.h>\nint subset_sum(const unsigned short*a,size_t n,size_t target,unsigned char*r){if(!a||!r||target==SIZE_MAX)return 0;for(size_t s=0;s<=target;s++)r[s]=0;r[0]=1;for(size_t i=0;i<n;i++)if(a[i])for(size_t s=target+1;s>a[i];){--s;if(r[s-a[i]])r[s]=1;}return r[target]!=0;}\n',
    },
    {
        "slug": "base-conversion", "title": "Unsigned base conversion", "family": "Arithmetic and number theory",
        "summary": 'Convert an unsigned word to base 2..16, uppercase digits, and append a terminator. Return digit count, or 0 before output writes on invalid base, null output or insufficient capacity.',
        "recognition": '1. Collect remainders in a 32-byte scratch buffer.\n2. Check space for digits and terminator.\n3. Reverse the digits into output.',
        "method": '1. Collect remainders in a 32-byte scratch buffer.\n2. Check space for digits and terminator.\n3. Reverse the digits into output.',
        "complexity": 'O(number of output digits).', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stddef.h>\nsize_t u32_to_base(unsigned v,unsigned b,char*out,size_t cap){if(!out||b<2||b>16)return 0;char d[32];size_t n=0;do{unsigned x=v%b;d[n++]=(char)(x<10?48+x:55+x);v/=b;}while(v);if(cap<=n)return 0;for(size_t i=0;i<n;i++)out[i]=d[n-1-i];out[n]=0;return n;}\n',
    },
    {
        "slug": "debounce-state-machine", "title": "Debounce state machine", "family": "Embedded streams and signals",
        "summary": 'Caller initializes stable/candidate/ticks. Require required>=1; samples are byte states. Return 1 for a valid update and set changed only when required consecutive samples confirm a new state.',
        "recognition": '1. A new candidate starts at one sample.\n2. Repeated samples increment the counter up to required.\n3. Publish a changed stable state at the threshold.',
        "method": '1. A new candidate starts at one sample.\n2. Repeated samples increment the counter up to required.\n3. Publish a changed stable state at the threshold.',
        "complexity": 'O(1) time and space per sample.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stdint.h>\ntypedef struct{uint8_t stable,candidate;uint16_t ticks;}Debounce;int debounce_update(Debounce*s,uint8_t sample,uint16_t required,uint8_t*changed){if(s==0||changed==0||required==0u)return 0;*changed=0u;if(sample!=s->candidate){s->candidate=sample;s->ticks=1u;}else if(s->ticks<required)++s->ticks;if(s->ticks==required&&s->stable!=s->candidate){s->stable=s->candidate;*changed=1u;}return 1;}\n',
    },
    {
        "slug": "threshold-hysteresis", "title": "Threshold hysteresis", "family": "Embedded streams and signals",
        "summary": 'Require low<high and a state pointer. While off, turn on at sample>=high; while on, turn off at sample<=low. Retain state inside the band. Return 0 on invalid input, otherwise 1.',
        "recognition": '1. Read the current state.\n2. Apply its corresponding threshold.\n3. Retain state inside the band.',
        "method": '1. Read the current state.\n2. Apply its corresponding threshold.\n3. Retain state inside the band.',
        "complexity": 'O(1) per sample.', "history": 'Possible variation', "questions": [],
        "code": '#include <stdint.h>\n#include <stddef.h>\n#include <limits.h>\n#include <stdint.h>\nint hysteresis_update(uint16_t sample,uint16_t low,uint16_t high,uint8_t*state){if(state==0||low>=high)return 0;if(*state==0u&&sample>=high)*state=1u;else if(*state!=0u&&sample<=low)*state=0u;return 1;}\n',
    },
]

# Every consumer receives the complete maintained C/ARM entries.
import existing_algorithm_repairs
