"""Curated lesson-to-pattern relationships; no keyword-only guesswork."""
RELATED = {
"c-program":["Build recovery and submission"],
"c-values":["Clamp absolute saturation and overflow"],
"c-decisions":["Joystick event state machine"],
"c-loops":["Word-array traversal","Balanced early exit from inner search"],
"c-functions":["Four-register argument contract"],
"c-bits":["Bitfield extraction insertion and packing","APSR flag contract"],
"c-pointers":["Word-array traversal","Row-major matrix addressing"],
"c-collections":["Signed and unsigned byte arrays","Bounded string primitives","Row-major matrix addressing"],
"c-state":["Restart and persistent state"],
"c-files":["Exclusive interrupt-vector ownership","Assembly objects and exported symbols"],
"c-events":["Event flags counters and queues","Atomic ISR event handoff"],
"c-integration":["Assembly stub to real integration"],
"arm-machine":["Four-register argument contract"],
"arm-file":["Assembly objects and exported symbols"],
"arm-contract":["Question prose to a contract","Four-register argument contract"],
"arm-flags":["APSR flag contract"],
"arm-constants":["Assembly objects and exported symbols"],
"arm-memory":["Signed and unsigned byte arrays","Word-array traversal"],
"arm-loops":["Nested loops with preserved outer state","Balanced early exit from inner search"],
"arm-layout":["Row-major matrix addressing","Packed 8x8 bit-matrix transpose"],
"arm-stack":["Non-leaf prologue and epilogue","Register preservation and stack safety"],
"arm-extra":["Fifth and later arguments"],
"arm-wide":["Fixed-point multiply and recurrence","Signed 64-by-32 restoring division","Indirect-index recurrence"],
"arm-recursion":["Recursive DFS with depth contract","Bounded DFS with an explicit stack"],
"arm-exceptions":["MSP/PSP exception-frame selection","SVC immediate decoding"],
"arm-debug":["Register preservation and stack safety","Build recovery and submission"],
"board-start":["Multi-peripheral ownership plan"],
"board-leds":["Bitfield extraction insertion and packing"],
"board-buttons":["GPIO event capture","Deterministic debounce"],
"board-irq":["Exclusive interrupt-vector ownership"],
"board-timers":["Timer setup and ownership","Periodic match scheduling"],
"board-debounce":["Deterministic debounce"],
"board-systick":["Periodic match scheduling","Exclusive interrupt-vector ownership"],
"board-rit":["Multi-peripheral ownership plan","Deterministic debounce"],
"board-joystick":["Joystick event state machine","Restart and persistent state"],
"board-adc":["ADC sample conversion"],
"board-dac":["DAC table streaming"],
"board-events":["Event flags counters and queues","Atomic ISR event handoff"],
"board-combine":["Multi-peripheral ownership plan"],
"board-power":["ISR-to-foreground event loop","Atomic ISR event handoff"],
"board-interface":["Adapt a partial pattern match"],
"board-lcd":["Row-major matrix addressing","Bitfield extraction insertion and packing"],
"project-buttons":["Deterministic debounce","Joystick event state machine"],
"project-timed":["Assembly stub to real integration","Word-array traversal"],
"project-analog":["ADC sample conversion","Multi-peripheral ownership plan"],
"practice-exam":["Question prose to a contract","Build recovery and submission"],
}
