"""Pattern-specific teaching. Rows are reviewed separately from code sources.
Fields: title | use | avoid | method | trace | tests | adaptation.
"""
ROWS = r"""
Signed and unsigned array sorting|Sort bytes/words in required ascending order|Do not choose signed branches for unsigned keys|Copy if input must survive; select the smallest remaining element; exchange it with the first unsorted position; repeat|[3,-1,2] -> [-1,3,2] -> [-1,2,3]|empty; one; equal; signed minimum; high-bit unsigned|Choose load width and comparison signedness; use the unsigned comparison variant for high-bit unsigned keys
Bounded recurrence into an array|Generate n terms from fixed seeds|Not a loop that may read terms not yet produced|Write available seeds only; begin at first nonseed index; compute from old terms; check output capacity before each store|The indirect-recurrence baseline starts with0; each next term uses the documented subtract-or-add rule and uniqueness test|n=0,1,2; exact capacity; overflow at first computed term|Change recurrence/seed count, not the initialized-prefix invariant
Matrix and graph traversal|A grid encodes neighbor or connectivity relationships|A flat scan alone does not find reachability|Define row stride and valid neighbors; initialize visited; traverse bounded work storage; mark once|2x3 grid: (1,2) index=5, not 1*2+2|rectangular grid; boundary cells; disconnected nodes; cycle|Choose DFS/BFS/cost algorithm from required result, not matrix appearance
Frequency-count comparison|Compare multiplicities where order does not matter|Cannot replace positional matching when positions contribute separately|Zero bounded histograms; validate each symbol; count both inputs; sum minimum counts|[1,1,2] and [1,2,2]: min counts 1+1=2|all repeated; disjoint symbols; out-of-domain input|If computing bulls/cows, subtract positional matches from total multiplicity matches
Fixed-point multiply and recurrence|Multiply scaled integers while generating terms|Do not rescale before widening the product|State fractional bits; form wide signed/unsigned product; apply specified rounding; range-check; store next term|Q8 384*384=147456; >>8=576 representing 2.25|zero; negative; saturation threshold; seed-only count|Change scale and rounding explicitly; keep intermediate width sufficient
Nested loops with preserved outer state|Rows, pair comparisons, or inner searches|Do not reuse outer index/register as inner scratch|Keep outer bound and index live; reset inner index for each outer iteration; update outer once|2 outer x 3 inner -> (0,0..2), then (1,0..2)|zero outer; zero inner; 1xN; inner helper clobbers scratch|Preserve outer state across BL and early inner exits
Balanced early exit from inner search|Return/break as soon as a match is found|A branch that bypasses stack restoration is unsafe|Define not-found sentinel; check bounds; branch to shared success/failure epilogue; restore every saved register|[4,7,9],key=7 -> test index0 then index1 -> return1|first; last; absent; empty|Change match predicate while keeping shared cleanup paths
Signed and unsigned byte arrays|Data elements occupy one byte|Word loads may read unrelated elements and beyond bounds|Select LDRSB or LDRB; compare with matching signedness; store STRB; increment by1|0xFE -> LDRSB=-2; LDRB=254|0x00,0x7F,0x80,0xFF; one byte|Byte size and signed interpretation are separate choices
Word-array traversal|Scan contiguous 32-bit objects|Not suitable unchanged for packed bytes|Check n before loading; compute base+4*i; update accumulator; increment i|[2,4,6] at offsets0,4,8 -> sum12|empty; one; exact n; guard words unchanged|Choose pointer stepping OR scaled indexing, not both
Row-major matrix addressing|Flat rectangular rows with known column count|Not equivalent to pointer-to-pointer or column-major storage|Validate r,c; calculate r*cols+c; scale by element size; load/store once|2x3 words (1,2) -> index5 -> byte20|non-square; first/last coordinate; invalid row/column|Change cols/width; preserve a single scaling step
Four-register argument contract|At most four ordinary word arguments|Not a universal rule for doublewords or structs|Write exact C prototype; map words R0-R3; preserve needed inputs; return required value|f(a,b,c,d) starts a=R0,b=R1,c=R2,d=R3|distinct argument values; zero; caller preserved registers|Keep symbol, types, and argument order synchronized
Fifth and later arguments|Ordinary word arguments spill to caller stack|Do not use entry offsets after allocating a frame|Record entry SP; count frame bytes including padding; load fifth at newSP+frame; restore frame|PUSH two words -> fifth at SP+8|different fifth/sixth values; changed prologue; alignment|Recompute offsets after every save-set change
Non-leaf prologue and epilogue|A function executes BL or BLX|Saving LR after the nested call is too late|Save original LR and changed callee registers; maintain alignment; preserve live scratch; restore one exit|SP=S -> PUSH R4,LR -> S-8 -> BL -> POP -> S|multiple calls; early failure; caller sentinels|Account for locals and extra arguments in the same frame diagram
APSR flag contract|Carry, overflow, or signed comparisons affect the answer|Do not assume every instruction updates flags|Select flag-setting instruction; consume intended C/V/Z/N before clobber; branch with correct interpretation|0xFFFFFFFF+1: C=1; signed 0x7FFFFFFF+1: V=1|carry without signed overflow; signed overflow without carry; equality|State which flag represents the paper's failure condition
SVC immediate decoding|An SVC number selects an exception service|Handler PC is not the interrupted stacked PC|Locate interrupted frame; read instruction at stackedPC-2; decode immediate; update stacked result when required|stackedPC after SVC #5 -> byte at PC-2 contains5|different immediates; MSP/PSP contexts; result delivery|Keep frame selection and dispatcher ownership explicit
MSP/PSP exception-frame selection|Wrapper must find the interrupted hardware frame|Always choosing MSP fails for PSP thread mode|Inspect EXC_RETURN stack-select bit; read matching stack pointer; pass frame to dispatcher|EXC_RETURN bit2=0 -> MSP; bit2=1 -> PSP|both stack selections; untouched stacked LR/PC/xPSR|Do not replace exception-return semantics with ordinary BX caller logic
Timer setup and ownership|Configure a requested periodic or one-shot event|Two owners reconfiguring one timer conflict|State units/clock/mode; configure; check status; start last; acknowledge once per IRQ|config500ms -> stopped -> start -> match -> clear|failed config; restart; simultaneous enabled flags|Use actual timer PCLK and preserve exact handler ownership
GPIO event capture|Capture a value when an input event occurs|Polling later may observe a different time-dependent value|Acknowledge/debounce as required; capture at required event instant; transfer value and ready state safely|Timer count123 at press, main runs at130: captured result remains123|back-to-back events; release; queue full|State raw-edge versus confirmed-press capture timing
Joystick event state machine|Different actions apply in edit/display states|A held level must not automatically become many presses|Sample levels; derive stable edges; process state-specific action; update previous sample|0,left,left,0,left -> two left events|hold; release; simultaneous directions; restart|Separate edge detection, debounce, and optional key repeat
ADC sample conversion|Process a fresh analog measurement|Starting a conversion does not immediately produce a result|Initialize; start once; capture in ADC IRQ; take if fresh; scale to output range|sample4095 -> endpoint-scaled DAC1023|0;4095; no fresh value; next conversion|Use correct 12-bit source width and explicit rounding
DAC table streaming|Repeated table samples form a timed waveform|Coalescing flags can lose required sample ticks|Initialize DAC; choose sample frequency; write one sample per tick; wrap index; silence on stop|4 samples at4kHz -> waveform1kHz|last index; restart; bounds0..1023; stop level|Distinguish sample rate from waveform frequency
ISR-to-foreground event loop|Short IRQ publishes pending work|Flags do not preserve every occurrence|Acknowledge hardware; publish named bit; atomically take in main; process bounded work|setA,setA,takeA -> one pendingA|no events; A+B; event during consume|Use counters/queues when count or payload matters
Deterministic debounce|One event per stable press|A delay loop in the IRQ is not a reliable sample clock|Configure true tick interval; begin on edge; tick periodically; consume confirmed event; release/re-arm|10ms samples with50ms confirmation -> stable-press event|bounce; hold; release; second press|10/50ms is a teaching recipe; use specified timing when different
Periodic match scheduling|Maintain repeated timing over many intervals|Resetting from delayed foreground can accumulate drift|Choose reset-on-match or advance compare from previous deadline; acknowledge; bound delayed catch-up|deadlines100,200,300 remain scheduled even if servicing at205|late service; wrap; missed multiple intervals|State whether to catch up, drop, or count missed deadlines
Free-running timer seed|Sample timing-dependent counter as a seed|A modulo counter is not full-range free-running|Choose counter mode/range; start once; capture required instant; apply requested seed mapping|TC=37 mod16 -> seed5|zero; wrap boundary; repeated reset|Do not claim statistical randomness or reset counter on every read
Register preservation and stack safety|Any callable routine changes preserved storage|Correct result alone is not enough|Mark modified R4-R11; save/restore; balance SP on every exit; check alignment at calls|caller R4=0x1234 -> callee must return sameR4|early return; nested calls; register sentinels|Treat ABI checks as separate from output checks
Atomic ISR event handoff|Foreground and IRQ update shared state|volatile does not protect compound read/clear|Use take helpers or brief critical section; restore prior mask; copy payload consistently|read-clear protected -> new event after exit remains pending|IRQ before/during/after handoff; nested critical section|Choose bit/counter/queue and define overflow
Exclusive interrupt-vector ownership|One vector appears in startup and driver files|Adding a second handler causes duplicate definitions|Find existing owner; edit body there; keep vector name; review enabled sources|TIMER0 vector -> one TIMER0_IRQHandler -> all enabled Timer0 causes|duplicate symbol; default handler; wrong spelling|Do not disable unrelated driver groups to hide conflicts
Assembly objects and exported symbols|C and ARM share named data/function storage|EXPORT is not a C definition and extern allocates no storage|Choose one writable/read-only definition; export/import names; match widths/alignment; reference address correctly|DCD7 exported object -> extern uint32_t sees7|name mismatch; duplicate storage; const write|Validate structure offsets instead of guessing padding
Signed 64-by-32 restoring division|Exact wide signed quotient with limited primitives|Do not use a 32-bit divide that discards high dividend bits|Validate divisor; divide magnitudes bitwise with bounded loop; restore sign; check quotient range/remainder contract|-9/2 -> quotient-4,remainder-1 under truncation toward zero|zero divisor; negative operands; minimum magnitude; overflow|Keep sign, quotient width, and remainder definition explicit
Packed 8x8 bit-matrix transpose|Exchange row and column positions in 64 packed bits|Byte reversal alone is not transpose|Fix bit layout; extract bit(r,c); place at(c,r); preserve input if required|only bit(1,3)=1 -> only bit(3,1)=1|allzero; allone; identity; single bit at every position|Bit order and row packing must match the source contract
Packed binary matrix multiplication|Matrix product over a defined binary operation|Ordinary integer matrix multiply may use wrong algebra|Decode row/column bits; combine pairs; reduce with required XOR or OR; repack result|GF(2): [1,1] dot[1,1]=0, unlike Boolean-OR result1|identity; zero; distinction XOR versus OR|State algebra, dimensions, and bit layout before coding
Bounded DFS with an explicit stack|Depth-first traversal without recursive stack growth|An unbounded push can overflow the work array|Push start if valid; pop; mark/discover consistently; push valid unseen neighbors with capacity checks|0 connected1,2 -> visit0 then last-pushed neighbor|cycle; disconnected; capacity exhausted|Choose visited-at-push policy to avoid duplicate work growth
Component-label merge|Merge connectivity classes during edge processing|Relabeling one endpoint does not merge the whole class|Initialize labels; for each joining edge replace old class throughout labels; count distinct classes|labels[0,1,2],edges0-1,1-2 -> [0,0,0]|self-edge; duplicate edge; disconnected classes|O(VE) relabeling differs from union-find complexity
Five-argument linear congruential generator|Generate bounded pseudorandom recurrence with stack argument|Modulo and full-width wrap are not interchangeable|Map five arguments; compute widened multiply/add as required; reduce; write within capacity|a5,c1,m16,seed3 ->0,1,6|m=0 policy; n=0; seed-only; overflow|Match exact prototype and whether seed is output element zero
Run-length encoding|Compress consecutive equal runs|A histogram loses run ordering|Track current symbol/count; flush when value changes; bound output; flush final run|AAABB -> (A,3),(B,2)|empty; one; allsame; alternating; capacity one short|Define count width and split behavior for long runs
Bounded look-and-say generation|Describe successive runs of a sequence|Do not overwrite input while still scanning it|Read runs; append count and symbol using required encoding; check capacity; swap buffers per term|1 ->11 ->21 ->1211|empty policy; count>=10; full output; final run|Distinguish numeric tokens from decimal character encoding
Indirect-index recurrence|New terms reference earlier terms through data-derived indexes|An index not initialized yet invalidates the recurrence|Write seeds; compute both indexes; verify range and prior-term condition; load; combine|a1=a2=1, a3=a(3-a2)+a(3-a1)=2|seed-only; first derived term; zero/out-of-range index|Translate one-based mathematical indexes consistently to storage
Signed min max and sum reduction|Summarize signed values in one pass|Initializing max to zero fails all-negative inputs|Handle empty contract; initialize min/max from first element; widen sum if required; scan remainder|[-5,-2,-9] -> min-9,max-2,sum-16|empty; one; allnegative; sum overflow|Return values versus output pointers must match prototype
Consume-once duplicate-safe matching|Each item may match at most once|Counting every equal pair overcounts duplicates|Mark exact/consumed items; search only unused candidates; consume once; count|[1,1] versus[1,2] permits one match, not two|all duplicates; exact plus misplaced; exhausted candidates|Preserve separate used flags or equivalent multiplicity limits
Linear search variants|Find first/last/all matches in unsorted input|Cannot assume sortedness for early rejection|Choose result policy; scan bounded range; update/return on match; return documented absence|[4,7,4],key4 -> first0,last2,count2|empty; absent; duplicate; last|Choose sentinel type that can represent not-found
Binary search and lower bound|Sorted data supports interval halving|Wrong on unsorted data|Maintain half-open [lo,hi); mid=lo+(hi-lo)/2; move one boundary; return insertion point|[1,3,3,8],key3 -> lower_bound1|empty; beforefirst; afterlast; duplicates|State sort order and exact-match versus insertion-point result
In-place array reversal|Reverse element order without extra array|Reversing bytes of each word is different|Handle n<2; left=0,right=n-1; swap while left<right; move inward|[1,2,3,4] ->[4,2,3,1]->[4,3,2,1]|empty; one; odd/even|Preserve element width and avoid unsigned n-1 on empty input
Left and right array rotation|Circularly shift positions preserving all elements|A shift that discards endpoints is not rotation|Handle n=0; reduce k modulo n; use reversal or buffer method; choose direction|[1,2,3,4] left1 ->[2,3,4,1]|k0,k=n,k>n; empty; one|State left/right and whether mutation is allowed
Selection sort|Simple in-place ordering with few swaps|Not stable by default|For each destination find minimum of remaining suffix; swap once|[3,1,2] ->[1,3,2]->[1,2,3]|sorted; reverse; duplicates; signed values|Keep minimum index separate from scanning index
Bubble sort with early termination|Small arrays and easy adjacent comparison|Not efficient for large worst-case input|Compare neighbors through unsorted suffix; swap inversion; shrink bound; stop if no swaps|[3,1,2]->[1,2,3] in first pass; next verifies no swaps|empty; one; already sorted; duplicates|Reset swapped flag each pass and use correct signedness
Stable merge sort|Stable O(n log n) ordering with scratch storage|Do not ignore temporary-buffer capacity|Split ranges; sort halves; merge by selecting left on equality; copy remainder|[2a,1] and[2b,3] ->[1,2a,2b,3]|odd sizes; equal keys with identity; scratch one short|Preserve tie rule and account for recursive stack depth
Partition-based quicksort|In-place average-fast ordering|Naive recursion can become deep on bad pivots|Choose pivot; partition with explicit interval convention; ensure equal keys progress; recurse smaller ranges|[3,1,2] pivot2 ->[1,2,3]|allsame; sorted; reverse; empty partitions|Document partition return meaning; bound worst-case stack
Heap construction and heap sort|In-place sorting via a priority tree in an array|Heap order is not globally sorted order|Build max-heap bottom-up; swap root with end; shrink heap; sift root down|heap[3,1,2] -> move3 toend -> heap[2,1] ->[1,2,3]|n0,n1; only left child; duplicates|For zero-based heap children are2*i+1 and2*i+2
Bounded counting sort|Keys lie in a small known integer domain|Huge sparse key ranges waste memory|Validate keys; zero counts; count occurrences; emit in key order within output capacity|[2,0,2,1] -> counts[1,1,2] ->[0,1,2,2]|domain endpoints; invalid key; empty|State whether stability/payload preservation is required
Euclidean GCD and overflow-aware LCM|Find greatest common divisor and least common multiple|Multiplying first can overflow unnecessarily|Repeat (a,b)=(b,a%b) until b0; LCM uses (a/gcd)*b with overflow check|gcd(18,12): (12,6)->(6,0)=6; lcm36|zero operands; equal; coprime; wide product|Define signed-input normalization and lcm(0,x)
Prime testing and trial factorization|Test/divide small positive integers|Do not test divisor squared in a type that may overflow|Handle n<2; try divisors while d<=n/d; divide factors repeatedly; emit residual|12 -> factor2 twice ->3 -> factors2,2,3|0,1,2; perfect square; prime; repeated factors|Bound factor output capacity and choose trial step policy
Integer square root|Return floor(sqrt(n)) without floating point|Rounded floating sqrt can violate exact integer bounds|Maintain candidate interval; compare via division/wide product; return greatest square<=n|n15 ->3; n16 ->4|0,1; perfect squares; max unsigned|Assert r*r<=n<(r+1)^2 using overflow-safe verification
Exponentiation by squaring|Compute integer a^n in logarithmic multiplications|Unchecked intermediates may overflow quickly|Start result1; if exponent bit set multiply; square base; shift exponent; apply defined overflow/modulo rule|3^5: result3,base9; base81; result243|exponent0; base0; large overflow; modulo policy|Define 0^0 and avoid unused final squaring overflow
Decimal digit algorithms|Extract/sum/reverse base-10 digits|Treating ASCII codes as numeric digits is wrong|Use quotient=n/10,remainder=n-10*q; process remainder; repeat q; handle zero explicitly|407 ->digits7,0,4 ->sum11|0; powers10; trailing zeros; reversal overflow|Choose digit order and retain leading zeros only if contract says so
Population count and parity|Count set bits or decide odd/even number of ones|Not the same as numeric value parity|Repeatedly clear lowest set bit with x&=x-1; increment count; parity=count&1|0b10110 ->3 set bits ->parity1|zero; onehot; allones|Operate on unsigned width and define parity convention
Bitfield extraction insertion and packing|Encode several bounded values in one word|OR alone does not replace an existing field|Validate widths; extract with shift/mask; clear destination field; insert masked new bits|0xAB replace bits4..7 with3 ->0x3B|zero/full mask; adjacent fields; invalid shift32|Distinguish field width, shift, and physical LED order
Clamp absolute saturation and overflow|Bound results or convert signed magnitude safely|abs(INT_MIN) is not representable as positive int32|Check limits before risky operation; widen if needed; choose saturate/error/wrap|clamp(-3,0,10)=0; clamp12=10|INT_MIN; exact limits; justoutside|Write overflow policy before choosing branch conditions
Prefix sums and range sums|Repeated interval-sum queries|Input updates require rebuilding or another structure|Prefix[0]=0; prefix[i+1]=prefix[i]+a[i]; query[l,r)=prefix[r]-prefix[l]|[2,4,6] ->[0,2,6,12]; [1,3)=10|empty interval; full range; invalid bounds; wide totals|Allocate n+1 entries and choose accumulator width
Histogram frequency and mode|Count values in a bounded domain and choose most frequent|No default tie rule is universally correct|Clear counts; validate/increment bins; scan bins using required tie rule|[2,1,2,1] ->tie; smallest-key rule returns1|empty; tie; invalid symbol; count overflow|State tie policy and whether empty has a sentinel
Horner polynomial evaluation|Evaluate coefficients efficiently|Coefficient order must be known|Start highest coefficient; repeatedly result=result*x+next; check intermediate width|2x^2+3x+4 atx2:2->7->18|degree0; x0; negative; overflow|Choose highest-first versus lowest-first layout explicitly
Moving average and sliding window|Repeated sums over a fixed-width window|Initializing from incomplete window changes semantics|Build first valid sum; remove outgoing value; add incoming; divide with specified rounding|[2,4,6,8],width2 ->sums6,10,14 ->means3,5,7|width0; width>n; width1; wide sum|Define warm-up behavior and signed division rounding
Bounded string primitives|Operate on terminated character sequences within capacity|No terminator within bounds must not cause runaway reads|Scan only capacity; identify zero; check destination including terminator; copy/compare bounded bytes|OK needs3 bytes: O,K,0|empty string; no terminator; exact capacity; overlap|State whether overlap is supported and whether output truncates
Overlap-safe memory movement|Copy regions that may overlap|Forward-only memcpy-style copying can corrupt source|Detect relative ranges; copy backward when destination starts inside source ahead; otherwise forward|ABCDE move4 bytes one right ->AABCD|same address; n0; both overlap directions; disjoint|Compare valid byte ranges and keep length units explicit
Checksums and CRC table structure|Detect accidental data changes using specified checksum|Different CRC parameters yield different valid-looking answers|Fix polynomial/init/reflection/xorout; process every byte; apply final transform|XOR checksum of1,2,3 ->0; not a CRC claim|empty message; known test vector; signed-byte input|Never substitute XOR sum for requested CRC; validate table provenance
Circular ring buffer|Fixed-capacity streaming data storage|An event bit cannot hold ordered payloads|Define head/tail/full convention; push with full check; pop with empty check; wrap indexes|capacity4 with one slot unused ->three queued items maximum|wrap; empty; full; producer/consumer race|State usable capacity and overflow policy
Array-backed stack|Bounded last-in-first-out storage|Not interchangeable with a FIFO queue|Top counts stored items; check before push; decrement before pop; never read empty|push1,push2,pop ->2 then1|empty pop; full push; one element|Keep capacity separate from top and define failure status
Circular queue|Bounded first-in-first-out traversal/work storage|Do not confuse index wrap with queue empty|Track count or reserved-slot convention; enqueue tail; dequeue head; wrap both|enqueue1,2; dequeue->1; enqueue3; order2,3|full; empty; wrap; repeated alternation|Choose one full/empty convention throughout
Singly linked-list operations|Nodes link through next pointers|Contiguous indexing does not follow arbitrary nodes|Validate head; walk pointers; preserve next before mutation; update head for first-node changes|1->2->3 remove2 ->1->3|empty; head removal; tail; missing key; cycle assumption|State node lifetime and whether memory allocation is allowed
Breadth-first search|Count reachable vertices using breadth-first traversal|The baseline returns a count, not distances or a reconstructed shortest path|Clear seen; mark start at enqueue; pop FIFO; enqueue unseen neighbors; return visited count|chain0-1-2 from0 reaches3 vertices|unreachable; cycle; queue capacity; start=goal|Use queue not stack and retain parent only if path required
Recursive DFS with depth contract|Depth-first recursion with explicit maximum depth|Visited state is still necessary for cyclic graphs|Check node/depth; mark visited before children; preserve frame; propagate depth failure|0->1->0 stops because0 already visited|depth0; cycle; long chain; branching|Define depth units and error return without leaving partial state ambiguous
Flood fill and maze propagation|Mark a connected region from a seed|Diagonal movement must not appear unless allowed|Validate seed; mark on enqueue; inspect specified neighbors; bound work storage|2x2 open grid with four-neighbor motion reaches4 cells|blocked seed; border; diagonal-only contact; full queue|Choose connectivity4/8 and whether source grid is mutated
Dijkstra shortest path|Shortest cost with nonnegative edge weights|Negative weights invalidate the greedy step|Initialize distances; select smallest unsettled; relax safe finite edges; mark settled|0->1 cost2,0->2 cost5,1->2 cost1 ->dist2=3|unreachable; zero edge; large infinity; addition overflow|Define no-edge representation separately from valid zero cost
Union-find with compression and rank|Repeated component membership and union queries|It does not directly return shortest paths|Initialize parent[i]=i; find roots with compression; union roots by rank; update rank on tie|union0,1 then1,2 ->find0=find2|same-set union; isolated node; invalid index|Preserve parent-tree invariant and bounded find behavior
Bounded zero-one knapsack|Choose each item at most once within capacity|Ascending one-dimensional updates reuse an item|Initialize DP; for each item iterate capacity downward; compare take/not-take|item weight2,value3,capacity4 ->value3 not6|zero items; overweight item; exact fit; capacity0|State zero-weight policy and whether reconstruction is required
Coin change|Count ways or minimize coins under a stated supply policy|These are distinct problems with different transitions|Choose objective and unlimited/bounded policy; initialize base dp0; select iteration order; handle unreachable|coins1,2 amount3: combinations2; ordered sequences3|min target0; unreachable; duplicate coins; count overflow|Name combinations/permutations/minimum explicitly
Longest increasing subsequence|Find a strictly increasing subsequence, not necessarily contiguous|A longest increasing contiguous run is different|For each element compare earlier smaller values; DP=1+best; track global maximum|[3,1,2,5] ->LIS1,2,5 length3|empty; duplicates; decreasing; allsame|Strict < differs from nondecreasing <=; decide reconstruction needs
Edit distance|Minimum insert/delete/substitute operations between sequences|Distance is not automatically an alignment reconstruction|Initialize empty-prefix row/column; compare characters; take minimum insertion/deletion/substitution|cat ->cut requires one substitution|both empty; one empty; repeated chars; unequal lengths|State operation costs and allocate bounded DP storage
"""
PATTERNS = {}
for line in ROWS.strip().splitlines():
    parts = line.split("|")
    assert len(parts) == 7, parts[0]
    PATTERNS[parts[0]] = dict(zip(("title","use","avoid","method","trace","tests","adapt"),parts))

WORKFLOWS = [
("Question prose to a contract", "Turn a new question into inputs, outputs, constraints, and tests", "Do not choose a familiar algorithm before reading exceptions",
 "Underline action verbs and constraints; write the exact prototype; separate input from output capacity; list empty/limit rules; make three hand-computable tests",
 "Return zero on overflow is different from wrapping: test just below and just above the boundary",
 "Normal input; smallest allowed input; first invalid/overflow case",
 "Copy exact function/handler names and constants; never infer a missing contract from an old solution"),
("Assembly stub to real integration", "Develop board behavior before the computation is finished", "A stub's successful build is not a completed answer",
 "Export exact symbol; return an obvious temporary value; build C call; test board path; replace stub; retest known algorithm cases; mark stub removed",
 "Stub returns10; LED display checked; real function returns12 for[2,4,6]; verify12 at debugger before display",
 "Symbol linkage; real result; zero/one inputs; no temporary constants",
 "Keep exact argument order and preserve caller registers when replacing the stub"),
("Multi-peripheral ownership plan", "Combine timers, input sampling, ADC, and output", "Two features cannot independently configure the same timer",
 "List resource/period/vector/producer/consumer; initialize state; test each device; connect one event path; start producers last",
 "RIT10ms samples inputs while Timer0 emits DAC samples; pausing playback leaves RIT alive",
 "Simultaneous IRQs; pause/resume; failed configuration; repeated round",
 "Separate resource lifetime from game-state lifetime and retain required input clocks"),
("Event flags counters and queues", "Choose how much event information survives scheduling", "A flag discards multiplicity and payload",
 "Ask whether presence,count,or ordered samples are required; choose bit,counter,or queue; protect handoff; define full/overflow policy",
 "Three presses before main: bit reports presence; counter reports3; queue can retain three captured values",
 "Burst; consumer delay; full buffer; two sources arriving together",
 "Specify independent-event priority and avoid else-if unless mutual exclusion is intended"),
("Restart and persistent state", "Repeat input/result rounds without corrupting long-lived data", "Resetting every variable can erase the secret or calibration",
 "Partition persistent and per-round fields; define transition table; reset round fields only; keep input re-arm behavior; test winning state",
 "EDIT ->SHOW ->EDIT clears guess but keeps secret; FINISHED ignores further edit events",
 "First round; second round; hold/release; win; reset during pending work",
 "Use explicit initialization and restart functions with different responsibilities"),
("Adapt a partial pattern match", "Reuse a technique when the new contract differs", "Similar titles are not proof of interchangeable code",
 "Compare width,signedness,mutation,capacity,timing,ABI; list differences; adapt one dimension at a time; rerun distinguishing tests",
 "Word scan ->signed-byte scan changes stride4to1, LDRtoLDRSB, and signed comparison",
 "Case where old and new versions differ; all original boundary tests",
 "Keep shared invariants and never copy old magic constants without evidence"),
("Build recovery and submission", "Recover from a broken milestone and deliver the correct project", "A project outside the required collection folder may not be collected",
 "Save current work; fix first build error; restore last known working milestone in your copy if needed; build final; copy full project; reopen submitted copy; preserve exam version",
 "Working copy builds ->submitted copy opened from declared destination ->same sources and target build",
 "Wrong folder; missing source; temporary stub; duplicate handler; unsaved editor",
 "Use the actual sitting's collection instructions; do not hard-code a historical drive or duration"),
]
for title,use,avoid,method,trace,tests,adapt in WORKFLOWS:
    PATTERNS[title] = dict(title=title,use=use,avoid=avoid,method=method,trace=trace,tests=tests,adapt=adapt)

WORKFLOW_CASES = {
 "Question prose to a contract": ("Choose the ordered-binary project; define KEY1 as0 and KEY2 as1; cap input at32 bits; submit on INT0; reset entry after submit; verify the final source and target", "KEY2,KEY1,KEY1,KEY2,KEY2,KEY1 builds100110; INT0 publishes38 and resets bit_count to0"),
 "Assembly stub to real integration": ("Use the word-max project; declare array_max_u32; a temporary7 can test linkage; replace it with the supplied full scan; run high-bit and single-element cases; inspect the final test_main", "The completed scan on[0,0x80000000,7,UINT32_MAX] returnsUINT32_MAX; a surviving constant7 would fail"),
 "Multi-peripheral ownership plan": ("Use buttons-rit-timer; assign RIT10ms to debounce and Timer0 500ms to display; EINT handlers only begin sampling; start clocks last; pause only the display timer", "KEY1 stops Timer0 while RIT continues to sample; KEY2 resets and starts Timer0. The separate DAC duration variant assigns one timer to samples and one to termination"),
 "Event flags counters and queues": ("Run event-handoff to see merged notifications; run timer-periodic to count directly in its producer; run ordered-binary to retain button identity; run ring-buffer test_main for FIFO full/empty/wrap cases", "Three Timer0 calls before a take set one pending bit; direct timer IRQ counting reaches3; binary commands1,0,1 produce5 in order"),
 "Restart and persistent state": ("Use Bulls-and-Cows; capture secret once on first SELECT; edit guess; submit; on a losing result SELECT clears only guess; verify secret persists; finish on four correct digits", "Set seedTC=0x1111 for secret[1,1,1,1]; a zero guess loses; new round preserves secret; press each direction once then submit to win"),
 "Adapt a partial pattern match": ("Compare the unsigned-byte and signed-byte matrix projects; retain row-major offset arithmetic; change prototype and LDRB to LDRSB together; rerun the same high-bit byte case", "At row1,column0 of a2x3 matrix, byte0x80 returns128 unsigned and-128 signed; address and stride remain identical"),
 "Build recovery and submission": ("Open buttons-rit-timer sample.uvprojx; retain one copy of each handler; build the SW_Debug target; compare files with the replacement list; copy the full project to the sitting's specified destination; reopen and rebuild that copy", "The supplied final project contains main, EINT handlers, RIT sampling and Timer0 display; the replaced template IRQ files are empty so symbols are not duplicated"),
}
for _title,(_method,_trace) in WORKFLOW_CASES.items():
    PATTERNS[_title].update(method=_method,trace=_trace)

PATTERNS["Word-array traversal"].update(method="Require a valid nonempty array; load its first word; compare subsequent words using unsigned ordering; keep the maximum",trace="[0,0x80000000,7,UINT32_MAX] -> UINT32_MAX",tests="one element; high-bit unsigned values; exact n; input unchanged; n=0 is outside this maximum routine's contract",adapt="The baseline computes a maximum, not a sum. For an empty-input result, choose an explicit different contract")
PATTERNS["Row-major matrix addressing"].update(method="Caller supplies valid row and column; calculate row*columns+column; read one byte",trace="2x3 bytes at row1,column2 -> index5 -> byte offset5",tests="non-square; first/last valid coordinates; high-bit byte; invalid coordinates are outside this low-level accessor's contract")
PATTERNS["Fixed-point multiply and recurrence"].update(trace="Q15:32768*16384 shifted15 gives16384; multiplying that by16384 again gives8192",method="Form signed64-bit product; shift the combined high/low words right15; return the low32 result; feed it into the next call",tests="zero; positive; negative; repeated multiplication",adapt="The delivered Q15 routine truncates the shifted result and does not saturate; use a separately specified saturation policy when required")
PATTERNS["APSR flag contract"].update(method="Classify R0 by sign and zero; copy N/Z while clearing C/V; read APSR immediately in the assembly caller before C can clobber flags",trace="classify0 -> Z=1; classify-1 -> N=1; classify1 -> N=Z=0; C=V=0",tests="zero; negative; positive; immediately captured APSR",adapt="This example returns N/Z classification with C/V cleared. Arithmetic carry/overflow requires a different flag-producing operation")
def render(title, esc):
    d = PATTERNS[title]
    listing = "\n".join(f"{i}. {s.strip()}" for i,s in enumerate(d["method"].split(";"),1))
    return (
        f'<h2>How to recognize it</h2><p>{esc(d["use"])}.</p>'
        f'<h2>When not to use it</h2><p>{esc(d["avoid"])}.</p>'
        f'<h2>Inputs and outputs</h2><p>{esc(d["adapt"])}.</p>'
        f'<h2>Solving method</h2><pre><code class="language-text">{esc(listing)}</code></pre>'
        f'<h2>Worked trace</h2><p>{esc(d["trace"])}.</p>'
        f'<h2>C approach</h2><p>Make the contract explicit in types and parameters. {esc(d["adapt"])}.</p>'
        f'<h2>Assembly considerations</h2><p>Map this contract to registers, memory widths, and the frame before translating the steps. {esc(d["avoid"])}.</p>'
        f'<h2>Adaptation checklist</h2><p>{esc(d["adapt"])}.</p>'
        f'<h2>Boundary tests</h2><p>{esc(d["tests"])}.</p>'
        f'<h2>Common mistakes</h2><p>{esc(d["avoid"])}. Use the trace above to locate the first differing step.</p>'
    )
