const {chromium}=require('C:/Users/marwa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('node:url');const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const root=path.resolve(__dirname,'../01_GUIDES_AND_INDEXES/PORTAL');const out=path.join(__dirname,'.pattern-qa');fs.mkdirSync(out,{recursive:true});let checks=0;const check=(c,m)=>{assert(c,m);checks++};const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const name of ['patterns/signed-and-unsigned-array-sorting.html','patterns/timer-setup-and-ownership.html','patterns/joystick-event-state-machine.html','courses/pattern-projects.html','api/exam-timer-config-match.html','api/index.html']){
 await page.goto(pathToFileURL(path.join(root,name)).href);await page.locator('h1').waitFor();check(await page.locator('h1').count()===1,'One page heading');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Desktop overflow '+name);
 if(name.startsWith('patterns/')){check(await page.locator('[data-runnable-pattern]').count()===1,'Complete project section');check(await page.getByRole('link',{name:'Open complete Keil project',exact:true}).count()>0,'Project links');const variants=page.getByRole('navigation',{name:'Runnable variants'}).getByRole('link');check(await variants.count()>0,'Variant navigation');const last=variants.last();const anchor=await last.getAttribute('href');await last.click();check(new URL(page.url()).hash===anchor,'Variant target');await page.locator('[data-runnable-pattern]').scrollIntoViewIfNeeded();const code=page.locator('.copy-code').first();await code.click();check(await page.locator('.copy-status').first().textContent()!==null,'Copy feedback');}
 await page.screenshot({path:path.join(out,name.replaceAll('/','-')+'.png')});await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Narrow overflow '+name);await page.screenshot({path:path.join(out,'narrow-'+name.replaceAll('/','-')+'.png')});await page.setViewportSize({width:1440,height:1000});
}
check(errors.length===0,'Browser script errors');fs.writeFileSync(path.join(__dirname,'PATTERN_BROWSER_RESULTS.json'),JSON.stringify({checks,errors,pages:6,screenshots:fs.readdirSync(out)},null,2));console.log({checks,errors});}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
