"""Offline exam walkthrough: rules are confirmed by the user, not inferred."""
STEPS = [
("confirm","Confirm this sitting",
 "Before the timed work, read the actual exam instructions. Use this package only where those instructions permit it. The two supplied rule PDFs differ on duration and USB access; neither is silently chosen for you.",
 ["Record allowed materials, actual duration, required template/interface, and the exact collection destination.",
  "Confirm whether any files must be uploaded before the exam; do not assume a personal template or this entire package is approved.",
  "Enter a duration only if you want a suggested budget; leave it blank for a checklist without timing."],
 "You know what is allowed and where the final project must be collected."),
("prepare","Prepare a clean working copy",
 "Copy the complete approved template, not isolated source files. Keep startup, project configuration, and driver folders together.",
 ["Open the copied sample.uvprojx and verify you are editing the copy.",
  "Build the unchanged project. If it fails, use build/link recovery before adding answer logic.",
  "Identify Source/sample.c, Source/ASM_funct.s, and the existing IRQ owners. Save the clean baseline."],
 "An unchanged copy builds and you can point to the correct files."),
("read","Read both questions before choosing code",
 "Read both exercises completely, including notes, prototypes, constants, and exceptional behavior. A familiar title does not guarantee the same contract.",
 ["Write required outputs and deliverables for each question.",
  "Mark widths, signedness, array lengths/capacities, mutation rules, exact functions, peripherals, periods, and reset behavior.",
  "Identify one small correct milestone for each question so all available work is considered."],
 "Each requirement has a place in your contract or ownership table."),
("order","Choose an implementation order",
 "Choose assembly first when the computation is the clearest starting point, or board first when an exact-interface temporary stub unlocks that work. The guide follows your choice.",
 ["Assembly first: implement one hand-checkable case before adding peripherals.",
  "Board first: use a visibly temporary assembly stub with the real symbol/prototype, then prove one input/output action.",
  "Record every temporary stub or constant and reserve time to remove it."],
 "Both questions have a next action; no temporary stub is mistaken for completion."),
("contract","Define the contract and three test cases",
 "Write the interface before choosing registers or copying a pattern.",
 ["Map arguments and return values; draw entry SP and frame if stack arguments are involved.",
  "List input/output sizes, allowed modification, empty/limit rules, and overflow behavior.",
  "Choose normal, smallest allowed, and boundary/error cases with hand-computed expected outputs.",
  "For board logic, write current state + event -> next state + action, including simultaneous events and restart."],
 "You can explain what a correct answer does before executing it."),
("implement","Implement one testable behavior at a time",
 "Use the smallest matching pattern. Adapt differences in width, signedness, mutation, timing, and ABI deliberately.",
 ["Build after each small working change; save milestones in your own copy.",
  "Inspect the first wrong observation rather than editing several unrelated things.",
  "Keep handlers bounded and one owner per vector. Start Timer/RIT producers after shared state is ready.",
  "Replace every temporary stub with real behavior; verify using inputs that distinguish it from the stub."],
 "The next build contains one understood change and the current milestone works."),
("test","Integrate and test the real behavior",
 "Compilation proves only that the toolchain accepted the project. Output, calling convention, timing, and physical inputs need separate checks.",
 ["Run empty/one/boundary cases; inspect signed values, stride, output capacity, and unchanged inputs.",
  "Check restored SP/R4-R11 and stack alignment before nested calls.",
  "Verify enabled IRQ flags are acknowledged once from a saved snapshot; test simultaneous sources.",
  "Test press/hold/release/repress, restart, timing, and physical LED mapping on the actual board.",
  "Search your answer files for temporary stubs/constants and remove them."],
 "Your checks cover both questions and any remaining limitation is understood."),
("submit","Submit the complete project to the actual destination",
 "Use this sitting's collection instructions. A successful working copy in the wrong folder is not a submitted project.",
 ["Save every editor file and build the final version.",
  "Copy the complete project folder, including required source/configuration, to the recorded destination.",
  "Reopen the project FROM that destination and verify it is the final version; build there if permitted.",
  "Check project identity, filenames, required deliverables, and any explicit upload/collection acknowledgement."],
 "You have verified the collected/submitted copy, not just your working directory."),
("preserve","Preserve the exam version before corrections",
 "Do not overwrite the only record of what you submitted. Self-correction procedures are separate from your original timed work.",
 ["Keep an unchanged exam-version copy.",
  "Create a separate correction copy if the course requests later fixes.",
  "Follow the current official correction format and deadline; the supplied rule versions are references, not an assumed current policy."],
 "The original timed version remains recoverable and distinguishable from corrections."),
]
HELP = [
("build","Build or linker errors",
 ["Save first; read the earliest meaningful error and its file/line.",
  "Syntax/type error: inspect the statement and preceding brace/semicolon. Undefined symbol: check spelling, prototype, EXPORT, and project membership.",
  "Multiply defined handler: find the existing owner and keep exactly one definition. Do not remove unrelated driver groups.",
  "Rebuild the last known working milestone in your copy if needed; never reset the protected template to experiment."]),
("output","Incorrect output",
 ["Check input arguments in the debugger before entering the routine.",
  "Trace the first iteration that differs from a tiny expected example; check width, signedness, index scaling, bounds, and overflow.",
  "Check the returned numeric value before LED encoding. Check physical LED4..LED11 mapping separately.",
  "Retest the failing case and one previous passing case after the fix."]),
("fault","HardFault or a stuck exception",
 ["Pause and inspect the failing instruction and available fault/frame information.",
  "Check whether the address is valid, aligned, and within the intended buffer; distinguish a value from a pointer.",
  "Check SP balance, LR preservation, and any MSP/PSP frame selection.",
  "Do not enable competing fault wrappers during the exam without reviewing existing ownership. Reduce the failing input."]),
("interrupt","Interrupt does not fire",
 ["Check initialization status and pin/clock configuration.",
  "Timer/RIT need explicit start; successful SysTick configuration starts immediately.",
  "Confirm vector spelling, one owner, interrupt enable/mask state, and peripheral interrupt mode.",
  "Inspect pending hardware flags and the existing handler. Check that a different feature did not stop or reconfigure the source."]),
("bounce","Repeated or missing button events",
 ["Separate raw IRQ count from confirmed press events.",
  "Check debounce_begin in the one EINT owner and debounce_tick at the configured real interval.",
  "Confirm event consumption, release/re-arm, and that the sampling timer remains active.",
  "For joystick, retain previous level and distinguish edge detection from debounce and optional repeat."]),
("time","Time running short",
 ["Stop expanding features; save the current working version.",
  "Prioritize a correct buildable milestone for each question; avoid leaving one entirely untouched.",
  "Keep the exact interface and meaningful partial behavior. Do not disguise temporary stubs as solved computation.",
  "Reserve time for final build and collection-folder verification. Follow the actual paper's priorities, not a fixed historical schedule."]),
]
